<?php

use Illuminate\Database\Seeder;

class KnowledgeTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \Illuminate\Support\Facades\DB::table('knowledge')->insert([
            [
                'id' => 1,
                'code' => 'R11',
                'premise' => '{"0":"C7,>=,0.7"}',
                'conclusion' => 'F120',
                'reliability' => 0.8,
                'type' => 1,
            ],
            [
                'id' => 2,
                'code' => 'R12',
                'premise' => '{"0":"C7,<,0.7"}',
                'conclusion' => 'F114',
                'reliability' => 0.8,
                'type' => 1,
            ],
            [
                'id' => 3,
                'code' => 'R13',
                'premise' => '{"0":"C6,>=,0.7"}',
                'conclusion' => 'F119',
                'reliability' => 0.8,
                'type' => 1,
            ],
            [
                'id' => 4,
                'code' => 'R14',
                'premise' => '{"0":"C6,<,0.7"}',
                'conclusion' => 'F113',
                'reliability' => 0.8,
                'type' => 1,
            ],
            [
                'id' => 5,
                'code' => 'R15',
                'premise' => '{"0":"C5,>=,0.7"}',
                'conclusion' => 'F118',
                'reliability' => 0.8,
                'type' => 1,
            ],
            [
                'id' => 6,
                'code' => 'R16',
                'premise' => '{"0":"C4,<,0.7"}',
                'conclusion' => 'F111',
                'reliability' => 0.8,
                'type' => 1,
            ],
            [
                'id' => 7,
                'code' => 'R17',
                'premise' => '{"0":"C3,>=,0.7"}',
                'conclusion' => 'F116',
                'reliability' => 0.8,
                'type' => 1,
            ],
            [
                'id' => 8,
                'code' => 'R18',
                'premise' => '{"0":"C3,>=,0.7"}',
                'conclusion' => 'F117',
                'reliability' => 0.8,
                'type' => 1,
            ],
            [
                'id' => 9,
                'code' => 'R19',
                'premise' => '{"0":"C3,<,0.7"}',
                'conclusion' => 'F19',
                'reliability' => 0.8,
                'type' => 1,
            ],
            [
                'id' => 10,
                'code' => 'R110',
                'premise' => '{"0":"C3,<,0.7"}',
                'conclusion' => 'F110',
                'reliability' => 0.8,
                'type' => 1,
            ],
            [
                'id' => 11,
                'code' => 'R111',
                'premise' => '{"0":"C2,>=,0.7","1":"C4,>=,0.6"}',
                'conclusion' => 'F16',
                'reliability' => 0.8,
                'type' => 1,
            ],
            [
                'id' => 12,
                'code' => 'R112',
                'premise' => '{"0":"C2,<,0.7"}',
                'conclusion' => 'F14',
                'reliability' => 0.8,
                'type' => 1,
            ],
            [
                'id' => 13,
                'code' => 'R113',
                'premise' => '{"0":"C2,<,0.7"}',
                'conclusion' => 'F15',
                'reliability' => 0.8,
                'type' => 1,
            ],
            [
                'id' => 14,
                'code' => 'R114',
                'premise' => '{"0":"C2,<,0.7"}',
                'conclusion' => 'F16',
                'reliability' => 0.8,
                'type' => 1,
            ],
            [
                'id' => 15,
                'code' => 'R115',
                'premise' => '{"0":"C1,>=,0.7"}',
                'conclusion' => 'F12',
                'reliability' => 0.8,
                'type' => 1,
            ],
            [
                'id' => 16,
                'code' => 'R21',
                'premise' => '{"0":"F11,0.8,1.0","1":"F12,0.9,1.0","2":"F13,1.0,1.0"}',
                'conclusion' => 'F21',
                'reliability' => 0.8,
                'type' => 2,
            ],
            [
                'id' => 17,
                'code' => 'R22',
                'premise' => '{"0":"F14,0.7,0.8"}',
                'conclusion' => 'F22',
                'reliability' => 0.8,
                'type' => 2,
            ],
            [
                'id' => 18,
                'code' => 'R23',
                'premise' => '{"0":"F15,0.8,1.0","1":"F16,0.6,0.8"}',
                'conclusion' => 'F24',
                'reliability' => 0.8,
                'type' => 2,
            ],
            [
                'id' => 19,
                'code' => 'R24',
                'premise' => '{"0":"F17,0.4,0.6"}',
                'conclusion' => 'F25',
                'reliability' => 0.8,
                'type' => 2,
            ],
            [
                'id' => 20,
                'code' => 'R25',
                'premise' => '{"0":"F17,0.7,0.8"}',
                'conclusion' => 'F26',
                'reliability' => 0.8,
                'type' => 2,
            ],
            [
                'id' => 21,
                'code' => 'R26',
                'premise' => '{"0":"F19,0.7,1.0"}',
                'conclusion' => 'F28',
                'reliability' => 0.8,
                'type' => 2,
            ],
            [
                'id' => 22,
                'code' => 'R27',
                'premise' => '{"0":"F110,0.7,1.0"}',
                'conclusion' => 'F29',
                'reliability' => 0.8,
                'type' => 2,
            ],
            [
                'id' => 23,
                'code' => 'R28',
                'premise' => '{"0":"F111,0.7,1.0"}',
                'conclusion' => 'F210',
                'reliability' => 0.8,
                'type' => 2,
            ],
            [
                'id' => 24,
                'code' => 'R29',
                'premise' => '{"0":"F112,0.7,1.0"}',
                'conclusion' => 'F211',
                'reliability' => 0.8,
                'type' => 2,
            ],
            [
                'id' => 25,
                'code' => 'R210',
                'premise' => '{"0":"F113,0.7,1.0"}',
                'conclusion' => 'F212',
                'reliability' => 0.8,
                'type' => 2,
            ],
            [
                'id' => 26,
                'code' => 'R211',
                'premise' => '{"0":"F113,0.7,1.0"}',
                'conclusion' => 'F213',
                'reliability' => 0.8,
                'type' => 2,
            ],
            [
                'id' => 27,
                'code' => 'R212',
                'premise' => '{"0":"F114,0.7,1.0"}',
                'conclusion' => 'F214',
                'reliability' => 0.8,
                'type' => 2,
            ],
            [
                'id' => 28,
                'code' => 'R116',
                'premise' => '{"0":"C11,<,0.7"}',
                'conclusion' => 'F121',
                'reliability' => 0.8,
                'type' => 1,
            ],
            [
                'id' => 29,
                'code' => 'R117',
                'premise' => '{"0":"C14,<,0.7"}',
                'conclusion' => 'F120',
                'reliability' => 0.8,
                'type' => 1,
            ],
            [
                'id' => 30,
                'code' => 'R118',
                'premise' => '{"0":"C16,<,0.7"}',
                'conclusion' => 'F126',
                'reliability' => 0.8,
                'type' => 1,
            ],
            [
                'id' => 31,
                'code' => 'R119',
                'premise' => '{"0":"C18,<,0.7"}',
                'conclusion' => 'F122',
                'reliability' => 0.8,
                'type' => 1,
            ],
            [
                'id' => 32,
                'code' => 'R120',
                'premise' => '{"0":"C41,<,0.7"}',
                'conclusion' => 'F123',
                'reliability' => 0.8,
                'type' => 1,
            ],
            [
                'id' => 33,
                'code' => 'R121',
                'premise' => '{"0":"C42,<,0.7"}',
                'conclusion' => 'F124',
                'reliability' => 0.8,
                'type' => 1,
            ],
            [
                'id' => 34,
                'code' => 'R122',
                'premise' => '{"0":"C43,<,0.7"}',
                'conclusion' => 'F125',
                'reliability' => 0.8,
                'type' => 1,
            ],
            [
                'id' => 35,
                'code' => 'R123',
                'premise' => '{"0":"C44,<,0.7"}',
                'conclusion' => 'F126',
                'reliability' => 0.8,
                'type' => 1,
            ],
            [
                'id' => 36,
                'code' => 'R213',
                'premise' => '{"0":"F126,0.7,1"}',
                'conclusion' => 'F216',
                'reliability' => 0.8,
                'type' => 2,
            ],
            [
                'id' => 37,
                'code' => 'R214',
                'premise' => '{"0":"F125,0.7,1"}',
                'conclusion' => 'F217',
                'reliability' => 0.8,
                'type' => 2,
            ],
            [
                'id' => 38,
                'code' => 'R215',
                'premise' => '{"0":"F121,0.7,1"}',
                'conclusion' => 'F221',
                'reliability' => 0.8,
                'type' => 2,
            ],
            [
                'id' => 39,
                'code' => 'R216',
                'premise' => '{"0":"F122,0.7,1"}',
                'conclusion' => 'F220',
                'reliability' => 0.8,
                'type' => 2,
            ],
            [
                'id' => 40,
                'code' => 'R217',
                'premise' => '{"0":"F123,0.7,1"}',
                'conclusion' => 'F219',
                'reliability' => 0.8,
                'type' => 2,
            ],
            [
                'id' => 41,
                'code' => 'R218',
                'premise' => '{"0":"F124,0.7,1"}',
                'conclusion' => 'F218',
                'reliability' => 0.8,
                'type' => 2,
            ],
        ]);
    }
}
